server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    location /toolbox/ai-entegrator/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /toolbox/ai-entegrator/index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
